# Generated by Django 5.1.2 on 2024-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_user_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_id',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
